import { readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { EXPENSE_CATEGORIES, EXPENSE_CATEGORY_LABELS } from './expense-categories';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = path.resolve(__dirname, '../../../../apps/api/src/db/migrations');

describe('expense-categories', () => {
  it('EXPENSE_CATEGORY_LABELS keys match EXPENSE_CATEGORIES tuple', () => {
    const labelKeys = Object.keys(EXPENSE_CATEGORY_LABELS).sort();
    const tupleKeys = [...EXPENSE_CATEGORIES].sort();
    expect(labelKeys).toEqual(tupleKeys);
  });

  it('latest expenses migration CHECK clause contains every category', async () => {
    // The expenses migration generated by Task 6 is 0007_good_butterfly.sql.
    // We locate the latest .sql file containing the expenses_category_chk
    // constraint so this stays correct if a follow-up migration adds a value.
    const files = await readdir(MIGRATIONS_DIR);
    const sqlFiles = files.filter((f) => f.endsWith('.sql')).sort();

    let latestWithCheck: string | null = null;
    let latestContents = '';
    for (const file of sqlFiles) {
      const contents = await readFile(path.join(MIGRATIONS_DIR, file), 'utf8');
      if (contents.includes('expenses_category_chk')) {
        latestWithCheck = file;
        latestContents = contents;
      }
    }

    expect(latestWithCheck).not.toBeNull();

    // Extract the CHECK (category IN (...)) clause associated with
    // expenses_category_chk and assert every tuple value appears in it as a
    // single-quoted SQL string literal.
    const checkMatch = latestContents.match(
      /expenses_category_chk["']?\s+CHECK\s*\(\s*category\s+IN\s*\(([^)]*)\)\s*\)/i,
    );
    expect(checkMatch).not.toBeNull();
    const inList = checkMatch![1];

    for (const category of EXPENSE_CATEGORIES) {
      expect(inList).toContain(`'${category}'`);
    }
  });
});
