/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthPerformanceRouteImport } from './routes/_auth.performance'
import { Route as AuthOptionsRouteImport } from './routes/_auth.options'
import { Route as AuthImportRouteImport } from './routes/_auth.import'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthChangelogRouteImport } from './routes/_auth.changelog'
import { Route as AuthCalculatorRouteImport } from './routes/_auth.calculator'
import { Route as AuthBrokeragesRouteImport } from './routes/_auth.brokerages'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'
import { Route as AuthAccountingRouteImport } from './routes/_auth.accounting'
import { Route as AuthPositionsIndexRouteImport } from './routes/_auth/positions/index'
import { Route as AuthAdvisorIndexRouteImport } from './routes/_auth.advisor.index'
import { Route as AuthAccountsIndexRouteImport } from './routes/_auth/accounts/index'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth.settings.profile'
import { Route as AuthSettingsHelpRouteImport } from './routes/_auth.settings.help'
import { Route as AuthSettingsBillingRouteImport } from './routes/_auth.settings.billing'
import { Route as AuthSettingsAdvisorRouteImport } from './routes/_auth.settings.advisor'
import { Route as AuthSettingsAccountRouteImport } from './routes/_auth.settings.account'
import { Route as AuthPositionsPositionIdRouteImport } from './routes/_auth/positions/$positionId'
import { Route as AuthAdvisorNewRouteImport } from './routes/_auth.advisor.new'
import { Route as AuthAdvisorIdRouteImport } from './routes/_auth.advisor.$id'
import { Route as AuthAccountsAccountIdRouteImport } from './routes/_auth/accounts/$accountId'
import { Route as AuthAccountingTaxSummaryRouteImport } from './routes/_auth/accounting/tax-summary'
import { Route as AuthAccountingFeeRollupRouteImport } from './routes/_auth/accounting/fee-rollup'
import { Route as AuthAccountingExpensesRouteImport } from './routes/_auth/accounting/expenses'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerformanceRoute = AuthPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOptionsRoute = AuthOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImportRoute = AuthImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChangelogRoute = AuthChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalculatorRoute = AuthCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBrokeragesRoute = AuthBrokeragesRouteImport.update({
  id: '/brokerages',
  path: '/brokerages',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountingRoute = AuthAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPositionsIndexRoute = AuthPositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdvisorIndexRoute = AuthAdvisorIndexRouteImport.update({
  id: '/advisor/',
  path: '/advisor/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountsIndexRoute = AuthAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsHelpRoute = AuthSettingsHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsBillingRoute = AuthSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsAdvisorRoute = AuthSettingsAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsAccountRoute = AuthSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthPositionsPositionIdRoute = AuthPositionsPositionIdRouteImport.update({
  id: '/positions/$positionId',
  path: '/positions/$positionId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdvisorNewRoute = AuthAdvisorNewRouteImport.update({
  id: '/advisor/new',
  path: '/advisor/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdvisorIdRoute = AuthAdvisorIdRouteImport.update({
  id: '/advisor/$id',
  path: '/advisor/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountsAccountIdRoute = AuthAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountingTaxSummaryRoute =
  AuthAccountingTaxSummaryRouteImport.update({
    id: '/tax-summary',
    path: '/tax-summary',
    getParentRoute: () => AuthAccountingRoute,
  } as any)
const AuthAccountingFeeRollupRoute = AuthAccountingFeeRollupRouteImport.update({
  id: '/fee-rollup',
  path: '/fee-rollup',
  getParentRoute: () => AuthAccountingRoute,
} as any)
const AuthAccountingExpensesRoute = AuthAccountingExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthAccountingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accounting': typeof AuthAccountingRouteWithChildren
  '/admin': typeof AuthAdminRoute
  '/brokerages': typeof AuthBrokeragesRoute
  '/calculator': typeof AuthCalculatorRoute
  '/changelog': typeof AuthChangelogRoute
  '/dashboard': typeof AuthDashboardRoute
  '/import': typeof AuthImportRoute
  '/options': typeof AuthOptionsRoute
  '/performance': typeof AuthPerformanceRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/accounting/expenses': typeof AuthAccountingExpensesRoute
  '/accounting/fee-rollup': typeof AuthAccountingFeeRollupRoute
  '/accounting/tax-summary': typeof AuthAccountingTaxSummaryRoute
  '/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/advisor/$id': typeof AuthAdvisorIdRoute
  '/advisor/new': typeof AuthAdvisorNewRoute
  '/positions/$positionId': typeof AuthPositionsPositionIdRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/advisor': typeof AuthSettingsAdvisorRoute
  '/settings/billing': typeof AuthSettingsBillingRoute
  '/settings/help': typeof AuthSettingsHelpRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/accounts/': typeof AuthAccountsIndexRoute
  '/advisor/': typeof AuthAdvisorIndexRoute
  '/positions/': typeof AuthPositionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/accounting': typeof AuthAccountingRouteWithChildren
  '/admin': typeof AuthAdminRoute
  '/brokerages': typeof AuthBrokeragesRoute
  '/calculator': typeof AuthCalculatorRoute
  '/changelog': typeof AuthChangelogRoute
  '/dashboard': typeof AuthDashboardRoute
  '/import': typeof AuthImportRoute
  '/options': typeof AuthOptionsRoute
  '/performance': typeof AuthPerformanceRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/accounting/expenses': typeof AuthAccountingExpensesRoute
  '/accounting/fee-rollup': typeof AuthAccountingFeeRollupRoute
  '/accounting/tax-summary': typeof AuthAccountingTaxSummaryRoute
  '/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/advisor/$id': typeof AuthAdvisorIdRoute
  '/advisor/new': typeof AuthAdvisorNewRoute
  '/positions/$positionId': typeof AuthPositionsPositionIdRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/advisor': typeof AuthSettingsAdvisorRoute
  '/settings/billing': typeof AuthSettingsBillingRoute
  '/settings/help': typeof AuthSettingsHelpRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/accounts': typeof AuthAccountsIndexRoute
  '/advisor': typeof AuthAdvisorIndexRoute
  '/positions': typeof AuthPositionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/accounting': typeof AuthAccountingRouteWithChildren
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/brokerages': typeof AuthBrokeragesRoute
  '/_auth/calculator': typeof AuthCalculatorRoute
  '/_auth/changelog': typeof AuthChangelogRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/import': typeof AuthImportRoute
  '/_auth/options': typeof AuthOptionsRoute
  '/_auth/performance': typeof AuthPerformanceRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/accounting/expenses': typeof AuthAccountingExpensesRoute
  '/_auth/accounting/fee-rollup': typeof AuthAccountingFeeRollupRoute
  '/_auth/accounting/tax-summary': typeof AuthAccountingTaxSummaryRoute
  '/_auth/accounts/$accountId': typeof AuthAccountsAccountIdRoute
  '/_auth/advisor/$id': typeof AuthAdvisorIdRoute
  '/_auth/advisor/new': typeof AuthAdvisorNewRoute
  '/_auth/positions/$positionId': typeof AuthPositionsPositionIdRoute
  '/_auth/settings/account': typeof AuthSettingsAccountRoute
  '/_auth/settings/advisor': typeof AuthSettingsAdvisorRoute
  '/_auth/settings/billing': typeof AuthSettingsBillingRoute
  '/_auth/settings/help': typeof AuthSettingsHelpRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/accounts/': typeof AuthAccountsIndexRoute
  '/_auth/advisor/': typeof AuthAdvisorIndexRoute
  '/_auth/positions/': typeof AuthPositionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/accounting'
    | '/admin'
    | '/brokerages'
    | '/calculator'
    | '/changelog'
    | '/dashboard'
    | '/import'
    | '/options'
    | '/performance'
    | '/settings'
    | '/accounting/expenses'
    | '/accounting/fee-rollup'
    | '/accounting/tax-summary'
    | '/accounts/$accountId'
    | '/advisor/$id'
    | '/advisor/new'
    | '/positions/$positionId'
    | '/settings/account'
    | '/settings/advisor'
    | '/settings/billing'
    | '/settings/help'
    | '/settings/profile'
    | '/accounts/'
    | '/advisor/'
    | '/positions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/accounting'
    | '/admin'
    | '/brokerages'
    | '/calculator'
    | '/changelog'
    | '/dashboard'
    | '/import'
    | '/options'
    | '/performance'
    | '/settings'
    | '/accounting/expenses'
    | '/accounting/fee-rollup'
    | '/accounting/tax-summary'
    | '/accounts/$accountId'
    | '/advisor/$id'
    | '/advisor/new'
    | '/positions/$positionId'
    | '/settings/account'
    | '/settings/advisor'
    | '/settings/billing'
    | '/settings/help'
    | '/settings/profile'
    | '/accounts'
    | '/advisor'
    | '/positions'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_auth/accounting'
    | '/_auth/admin'
    | '/_auth/brokerages'
    | '/_auth/calculator'
    | '/_auth/changelog'
    | '/_auth/dashboard'
    | '/_auth/import'
    | '/_auth/options'
    | '/_auth/performance'
    | '/_auth/settings'
    | '/_auth/accounting/expenses'
    | '/_auth/accounting/fee-rollup'
    | '/_auth/accounting/tax-summary'
    | '/_auth/accounts/$accountId'
    | '/_auth/advisor/$id'
    | '/_auth/advisor/new'
    | '/_auth/positions/$positionId'
    | '/_auth/settings/account'
    | '/_auth/settings/advisor'
    | '/_auth/settings/billing'
    | '/_auth/settings/help'
    | '/_auth/settings/profile'
    | '/_auth/accounts/'
    | '/_auth/advisor/'
    | '/_auth/positions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/performance': {
      id: '/_auth/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthPerformanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/options': {
      id: '/_auth/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof AuthOptionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/import': {
      id: '/_auth/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthImportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/changelog': {
      id: '/_auth/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthChangelogRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calculator': {
      id: '/_auth/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AuthCalculatorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/brokerages': {
      id: '/_auth/brokerages'
      path: '/brokerages'
      fullPath: '/brokerages'
      preLoaderRoute: typeof AuthBrokeragesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounting': {
      id: '/_auth/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthAccountingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/positions/': {
      id: '/_auth/positions/'
      path: '/positions'
      fullPath: '/positions/'
      preLoaderRoute: typeof AuthPositionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/advisor/': {
      id: '/_auth/advisor/'
      path: '/advisor'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AuthAdvisorIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounts/': {
      id: '/_auth/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthAccountsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/help': {
      id: '/_auth/settings/help'
      path: '/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof AuthSettingsHelpRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/billing': {
      id: '/_auth/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthSettingsBillingRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/advisor': {
      id: '/_auth/settings/advisor'
      path: '/advisor'
      fullPath: '/settings/advisor'
      preLoaderRoute: typeof AuthSettingsAdvisorRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/account': {
      id: '/_auth/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthSettingsAccountRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/positions/$positionId': {
      id: '/_auth/positions/$positionId'
      path: '/positions/$positionId'
      fullPath: '/positions/$positionId'
      preLoaderRoute: typeof AuthPositionsPositionIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/advisor/new': {
      id: '/_auth/advisor/new'
      path: '/advisor/new'
      fullPath: '/advisor/new'
      preLoaderRoute: typeof AuthAdvisorNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/advisor/$id': {
      id: '/_auth/advisor/$id'
      path: '/advisor/$id'
      fullPath: '/advisor/$id'
      preLoaderRoute: typeof AuthAdvisorIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounts/$accountId': {
      id: '/_auth/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthAccountsAccountIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounting/tax-summary': {
      id: '/_auth/accounting/tax-summary'
      path: '/tax-summary'
      fullPath: '/accounting/tax-summary'
      preLoaderRoute: typeof AuthAccountingTaxSummaryRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/accounting/fee-rollup': {
      id: '/_auth/accounting/fee-rollup'
      path: '/fee-rollup'
      fullPath: '/accounting/fee-rollup'
      preLoaderRoute: typeof AuthAccountingFeeRollupRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/accounting/expenses': {
      id: '/_auth/accounting/expenses'
      path: '/expenses'
      fullPath: '/accounting/expenses'
      preLoaderRoute: typeof AuthAccountingExpensesRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
  }
}

interface AuthAccountingRouteChildren {
  AuthAccountingExpensesRoute: typeof AuthAccountingExpensesRoute
  AuthAccountingFeeRollupRoute: typeof AuthAccountingFeeRollupRoute
  AuthAccountingTaxSummaryRoute: typeof AuthAccountingTaxSummaryRoute
}

const AuthAccountingRouteChildren: AuthAccountingRouteChildren = {
  AuthAccountingExpensesRoute: AuthAccountingExpensesRoute,
  AuthAccountingFeeRollupRoute: AuthAccountingFeeRollupRoute,
  AuthAccountingTaxSummaryRoute: AuthAccountingTaxSummaryRoute,
}

const AuthAccountingRouteWithChildren = AuthAccountingRoute._addFileChildren(
  AuthAccountingRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsAccountRoute: typeof AuthSettingsAccountRoute
  AuthSettingsAdvisorRoute: typeof AuthSettingsAdvisorRoute
  AuthSettingsBillingRoute: typeof AuthSettingsBillingRoute
  AuthSettingsHelpRoute: typeof AuthSettingsHelpRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsAccountRoute: AuthSettingsAccountRoute,
  AuthSettingsAdvisorRoute: AuthSettingsAdvisorRoute,
  AuthSettingsBillingRoute: AuthSettingsBillingRoute,
  AuthSettingsHelpRoute: AuthSettingsHelpRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthAccountingRoute: typeof AuthAccountingRouteWithChildren
  AuthAdminRoute: typeof AuthAdminRoute
  AuthBrokeragesRoute: typeof AuthBrokeragesRoute
  AuthCalculatorRoute: typeof AuthCalculatorRoute
  AuthChangelogRoute: typeof AuthChangelogRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthImportRoute: typeof AuthImportRoute
  AuthOptionsRoute: typeof AuthOptionsRoute
  AuthPerformanceRoute: typeof AuthPerformanceRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthAccountsAccountIdRoute: typeof AuthAccountsAccountIdRoute
  AuthAdvisorIdRoute: typeof AuthAdvisorIdRoute
  AuthAdvisorNewRoute: typeof AuthAdvisorNewRoute
  AuthPositionsPositionIdRoute: typeof AuthPositionsPositionIdRoute
  AuthAccountsIndexRoute: typeof AuthAccountsIndexRoute
  AuthAdvisorIndexRoute: typeof AuthAdvisorIndexRoute
  AuthPositionsIndexRoute: typeof AuthPositionsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountingRoute: AuthAccountingRouteWithChildren,
  AuthAdminRoute: AuthAdminRoute,
  AuthBrokeragesRoute: AuthBrokeragesRoute,
  AuthCalculatorRoute: AuthCalculatorRoute,
  AuthChangelogRoute: AuthChangelogRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthImportRoute: AuthImportRoute,
  AuthOptionsRoute: AuthOptionsRoute,
  AuthPerformanceRoute: AuthPerformanceRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthAccountsAccountIdRoute: AuthAccountsAccountIdRoute,
  AuthAdvisorIdRoute: AuthAdvisorIdRoute,
  AuthAdvisorNewRoute: AuthAdvisorNewRoute,
  AuthPositionsPositionIdRoute: AuthPositionsPositionIdRoute,
  AuthAccountsIndexRoute: AuthAccountsIndexRoute,
  AuthAdvisorIndexRoute: AuthAdvisorIndexRoute,
  AuthPositionsIndexRoute: AuthPositionsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
